apiVersion: v2
name: my-stack
version: 0.1.0
dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://./charts/frontend"
  - name: backend
    version: 0.1.0
    repository: "file://./charts/backend"
  - name: postgresql
    version: 15.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: ingress-nginx
    version: 4.10.0
    repository: "file://./charts/ingress-nginx"
  - name: sealed-secrets
    version: 2.15.0
    repository: "file://./charts/sealed-secrets"